name: Ubuntu

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g esy@latest
        
      # Fetch Core
      - name: esy '@fetch-core'
        run: esy '@fetch-core'
      - name: esy '@fetch-core' test
        run: esy '@fetch-core' test

      # Fetch Native Lwt
      - name: esy '@fetch-native-lwt'
        run: esy '@fetch-native-lwt'
      - name: esy '@fetch-native-lwt' example:get
        run: esy '@fetch-native-lwt' example:get
